from app.models import db, Stock


# Adds a NASDAQ100 stocks:
def seed_stocks():
    stocks = [
        ["AAPL",	"Apple Inc."], 
        ["ABNB",	"Airbnb, Inc. Class A Common Stock"], 
        ["ADBE",    "Adobe Inc."], 
        ["ADI",     "Analog Devices, Inc."], 
        ["ADP",     "Automatic Data Processing, Inc."], 
        ["ADSK",	"Autodesk, Inc."], 
        ["AEP",     "American Electric Power Company, Inc."], 
        ["ALGN",	"Align Technology, Inc."], 
        ["AMAT",	"Applied Materials, Inc."], 
        ["AMD",     "Advanced Micro Devices, Inc."], 
        ["AMGN",	"Amgen Inc."], 
        ["AMZN",	"Amazon.com, Inc."], 
        ["ANSS",	"ANSYS, Inc."], 
        ["ASML",	"ASML Holding N.V. New York Registry Shares"], 
        ["ATVI",	"Activision Blizzard, Inc."], 
        ["AVGO",	"Broadcom Inc."], 
        ["BIDU",	"Baidu, Inc. ADS"], 
        ["BIIB",	"Biogen Inc."], 
        ["BKNG",	"Booking Holdings Inc."], 
        ["CDNS",	"Cadence Design Systems, Inc."], 
        ["CEG",     "Constellation Energy Corporation"], 
        ["CHTR",	"Charter Communications, Inc. Class A Common Stock New"], 
        ["CMCSA",	"Comcast Corporation Class A Common Stock"], 
        ["COST",	"Costco Wholesale Corporation"], 
        ["CPRT",	"Copart, Inc. (DE)"], 
        ["CRWD",	"CrowdStrike Holdings, Inc. Class A Common Stock"], 
        ["CSCO",	"Cisco Systems, Inc. (DE)"], 
        ["CSX",     "CSX Corporation"], 
        ["CTAS",	"Cintas Corporation"], 
        ["CTSH",	"Cognizant Technology Solutions Corporation Class A Common Stock"], 
        ["DDOG",	"Datadog, Inc. Class A Common Stock"], 
        ["DLTR",	"Dollar Tree Inc."], 
        ["DOCU",	"DocuSign, Inc."], 
        ["DXCM",	"DexCom, Inc."], 
        ["EA",      "Electronic Arts Inc."], 
        ["EBAY",	"eBay Inc."], 
        ["EXC",     "Exelon Corporation"], 
        ["FAST",	"Fastenal Company"], 
        ["FB",      "Meta Platforms, Inc. Class A Common Stock"], 
        ["FISV",	"Fiserv, Inc."], 
        ["FTNT",	"Fortinet, Inc."], 
        ["GILD",	"Gilead Sciences, Inc."], 
        ["GOOG",	"Alphabet Inc. Class C Capital Stock"], 
        ["GOOGL",	"Alphabet Inc. Class A Common Stock"], 
        ["HON",     "Honeywell International Inc."], 
        ["IDXX",	"IDEXX Laboratories, Inc."], 
        ["ILMN",	"Illumina, Inc."], 
        ["INTC",	"Intel Corporation"], 
        ["INTU",	"Intuit Inc."], 
        ["ISRG",	"Intuitive Surgical, Inc."], 
        ["JD",	    "JD.com, Inc. American Depositary Shares"], 
        ["KDP",     "Keurig Dr Pepper Inc."], 
        ["KHC",     "The Kraft Heinz Company"], 
        ["KLAC",	"KLA Corporation"], 
        ["LCID",	"Lucid Group, Inc."], 
        ["LRCX",	"Lam Research Corporation"], 
        ["LULU",	"lululemon athletica inc."], 
        ["MAR",     "Marriott International Class A Common Stock"], 
        ["MCHP",	"Microchip Technology Incorporated"], 
        ["MDLZ",	"Mondelez International, Inc. Class A Common Stock"], 
        ["MELI",	"MercadoLibre, Inc."], 
        ["MNST",	"Monster Beverage Corporation"], 
        ["MRNA",	"Moderna, Inc."], 
        ["MRVL",	"Marvell Technology, Inc."], 
        ["MSFT",	"Microsoft Corporation"], 
        ["MTCH",	"Match Group, Inc."], 
        ["MU",      "Micron Technology, Inc."], 
        ["NFLX",	"Netflix, Inc."], 
        ["NTES",	"NetEase, Inc. American Depositary Shares"], 
        ["NVDA",	"NVIDIA Corporation"], 
        ["NXPI",	"NXP Semiconductors N.V."], 
        ["ODFL",	"Old Dominion Freight Line, Inc."], 
        ["OKTA",	"Okta, Inc. Class A Common Stock"], 
        ["ORLY",	"O'Reilly Automotive, Inc."], 
        ["PANW",	"Palo Alto Networks, Inc."], 
        ["PAYX",	"Paychex, Inc."], 
        ["PCAR",	"PACCAR Inc."], 
        ["PDD",     "Pinduoduo Inc. American Depositary Shares"], 
        ["PEP",     "PepsiCo, Inc."], 
        ["PYPL",	"PayPal Holdings, Inc."], 
        ["QCOM",	"QUALCOMM Incorporated"], 
        ["REGN",	"Regeneron Pharmaceuticals, Inc."], 
        ["ROST",	"Ross Stores, Inc."], 
        ["SBUX",	"Starbucks Corporation"], 
        ["SGEN",	"Seagen Inc."], 
        ["SIRI",	"Sirius XM Holdings Inc."], 
        ["SNPS",	"Synopsys, Inc."], 
        ["SPLK",	"Splunk Inc."], 
        ["SWKS",	"Skyworks Solutions, Inc."], 
        ["TEAM",	"Atlassian Corporation Plc Class A Ordinary Shares"], 
        ["TMUS",	"T-Mobile US, Inc."], 
        ["TSLA",	"Tesla, Inc."], 
        ["TXN",     "Texas Instruments Incorporated"], 
        ["VRSK",	"Verisk Analytics, Inc."], 
        ["VRSN",	"VeriSign, Inc."], 
        ["VRTX",	"Vertex Pharmaceuticals Incorporated"], 
        ["WBA",     "Walgreens Boots Alliance, Inc."], 
        ["WDAY",	"Workday, Inc. Class A Common Stock"], 
        ["XEL",     "Xcel Energy Inc."], 
        ["ZM",      "Zoom Video Communications, Inc. Class A Common Stock"], 
        ["ZS",	    "Zscaler, Inc."]
    ]

    for stock in stocks:
        s = Stock(ticker_symbol=stock[0], company_name=stock[1])
        db.session.add(s)

    db.session.commit()


def undo_stocks():
    db.session.execute('TRUNCATE stocks RESTART IDENTITY CASCADE;')
    db.session.commit()
