"""added_stock_updated_at

Revision ID: f10ab4197d13
Revises: 98175f60f948
Create Date: 2022-02-20 12:31:26.407348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10ab4197d13'
down_revision = '98175f60f948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'updated_at')
    # ### end Alembic commands ###
