"""portfolio-price

Revision ID: 98175f60f948
Revises: 4607959ec867
Create Date: 2022-02-19 16:25:24.417483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98175f60f948'
down_revision = '4607959ec867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('portfolios', 'purchase_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('purchase_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('portfolios', 'price')
    # ### end Alembic commands ###
