"""updated_stock_model

Revision ID: 6a55d5914606
Revises: da5e936420c1
Create Date: 2022-02-16 20:44:02.289780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a55d5914606'
down_revision = 'da5e936420c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('stocks', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('stocks', 'company_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
