"""updated_stock_table

Revision ID: 4607959ec867
Revises: 5b7cd1cb418a
Create Date: 2022-02-19 15:47:03.563842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4607959ec867'
down_revision = '5b7cd1cb418a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('last_updated', sa.BigInteger(), nullable=False))
    op.alter_column('stocks', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('stocks', 'last_updated')
    # ### end Alembic commands ###
